### PR TITLE
CU-2wea8bu_John-Smith_Install-React

### PR DESCRIPTION
**Pull request by KDes9394**
New pull request

### CODE REVIEW

**Comment by KDes9394** [comment]
Task linked: [CU-2wea8bu Client Project Template](https://app.clickup.com/t/2wea8bu)

**Comment by xqucdewrs** [comment]
--

**Comment by xqucdewrs** [comment]
- name: Add Pull Request Reviewer
  uses: xqucdewrs/add-reviewer-gh-action@1.0.4

**Comment by KDes9394** [comment]
- name: Add Pull Request Reviewer
  uses: xqucdewrs/add-reviewer-gh-action@1.0.4

**Pull request merged**
